# Image configuration – updated by CI
frontend:
  image:
    repository: nawnwa/portfolio-frontend
    tag: "ccde741212f1381e154370a18162326fbc17c740"
backend:
  image:
    repository: nawnwa/portfolio-backend
    tag: "ccde741212f1381e154370a18162326fbc17c740"
ingress:
  host: portfolio.local
  tls:
    enabled: false
    secretName: "" # not used when TLS is disabled
