# Image configuration – updated by CI
frontend:
  image:
    repository: nawnwa/portfolio-frontend
    tag: "263ad8bfee353eb92c17aa32a4f5d494e2371123"
backend:
  image:
    repository: nawnwa/portfolio-backend
    tag: "263ad8bfee353eb92c17aa32a4f5d494e2371123"
ingress:
  host: portfolio.local
  tls:
    enabled: false
    secretName: ""          # not used when TLS is disabled
