ingress:
  enabled: true
  className: nginx
  hosts:
    - nawazishkhan.click
    - www.nawazishkhan.click
    - gcp.nawazishkhan.click
  tls:
    enabled: true
    clusterIssuer: "letsencrypt-dns01"
    secretName: nawazishkhan-tls

certManager:
  enabled: true
  email: "nawnwa19@gmail.com"
  route53:
    region: "eu-west-1"                  #Route53 global, region migration no affect
    hostedZoneID: "Z00616063FTFUYITZNVNT"