ingress:
  host: "*.nawazishkhan.click"
  tls:
    enabled: true
    clusterIssuer: "letsencrypt-dns01"
    hosts:
      - nawazishkhan.click
      - gcp.nawazishkhan.click
    secretName: nawazishkhan-tls

certManager:
  enabled: true
  email: "your-real-email@example.com"
  route53:
    region: "eu-west-1"
    hostedZoneID: "Z00616063FTFUYITZNVNT"