ingress:
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
  hosts:
    - azure.nawazishkhan.click
  tls:
    enabled: false
    secretName: ""
    clusterIssuer: ""