# Image configuration – updated by CI
frontend:
  image:
    repository: nawnwa/portfolio-frontend
    tag: "ae02ce172519e52e11f76070143728c5e001d143"
backend:
  image:
    repository: nawnwa/portfolio-backend
    tag: "ae02ce172519e52e11f76070143728c5e001d143"
ingress:
  host: portfolio.local
