# ── AKS-SPECIFIC VALUES ────────────────────────────────────────────────

# ── INGRESS ─────────────────────────────────────────────────────────────

ingress:
  enabled: true
  className: nginx
  hosts:
    - aks.nawazishkhan.click
    - www.aks.nawazishkhan.click
  tls:
    enabled: true
    secretName: portfolio-aks-tls
    clusterIssuer: "letsencrypt-prod"

# ── SERVICES ────────────────────────────────────────────────────────────

service:
  frontend:
    type: ClusterIP
  backend:
    type: ClusterIP

# ── SCALING ─────────────────────────────────────────────────────────────

replicas:
  frontend: 2
  backend: 2

# ── CERT-MANAGER ────────────────────────────────────────────────────────
# Enabled for now (HTTP and HTTPs)

certManager:
  enabled: true
  email: "nawnwa19@gmail.com"